/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FleetMessages.h
  Source: FleetMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_FLEETMESSAGES_H_
#define _DDSL_FLEETMESSAGES_H_


#ifdef __cplusplus
extern "C" {
#endif

#define ChargerFleetData_ChargeMode_Constants_MODE_CHARGE 1
#define ChargerFleetData_ChargeMode_Constants_MODE_UNCHARGE 2
#define ChargerFleetData_ChargerMode_Constants_MODE_IDLE 0
#define ChargerFleetData_ChargerMode_Constants_MODE_CHARGING 1
#define ChargerFleetData_ChargerMode_Constants_MODE_CHARGEFULL 2
#define ChargerFleetData_ChargerMode_Constants_MODE_ERROR 3
#define ChargerFleetData_ChargerMode_Constants_MODE_REQUEST_ERROR 4


typedef struct ChargerFleetData_ChargeMode
{
  uint32_t mode;
} ChargerFleetData_ChargeMode;

extern const dds_topic_descriptor_t ChargerFleetData_ChargeMode_desc;

#define ChargerFleetData_ChargeMode__alloc() \
((ChargerFleetData_ChargeMode*) dds_alloc (sizeof (ChargerFleetData_ChargeMode)));

#define ChargerFleetData_ChargeMode_free(d,o) \
dds_sample_free ((d), &ChargerFleetData_ChargeMode_desc, (o))


typedef struct ChargerFleetData_ChargerMode
{
  uint32_t mode;
} ChargerFleetData_ChargerMode;

extern const dds_topic_descriptor_t ChargerFleetData_ChargerMode_desc;

#define ChargerFleetData_ChargerMode__alloc() \
((ChargerFleetData_ChargerMode*) dds_alloc (sizeof (ChargerFleetData_ChargerMode)));

#define ChargerFleetData_ChargerMode_free(d,o) \
dds_sample_free ((d), &ChargerFleetData_ChargerMode_desc, (o))


typedef struct ChargerFleetData_ChargerState
{
  char * name;
  char * model;
  char * task_id;
  ChargerFleetData_ChargerMode mode;
} ChargerFleetData_ChargerState;

extern const dds_topic_descriptor_t ChargerFleetData_ChargerState_desc;

#define ChargerFleetData_ChargerState__alloc() \
((ChargerFleetData_ChargerState*) dds_alloc (sizeof (ChargerFleetData_ChargerState)));

#define ChargerFleetData_ChargerState_free(d,o) \
dds_sample_free ((d), &ChargerFleetData_ChargerState_desc, (o))


typedef struct ChargerFleetData_ModeRequest
{
  char * fleet_name;
  char * charger_name;
  ChargerFleetData_ChargeMode mode;
  char * task_id;
} ChargerFleetData_ModeRequest;

extern const dds_topic_descriptor_t ChargerFleetData_ModeRequest_desc;

#define ChargerFleetData_ModeRequest__alloc() \
((ChargerFleetData_ModeRequest*) dds_alloc (sizeof (ChargerFleetData_ModeRequest)));

#define ChargerFleetData_ModeRequest_free(d,o) \
dds_sample_free ((d), &ChargerFleetData_ModeRequest_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_FLEETMESSAGES_H_ */
