module ChargerFleetData
{
  module ChargerMode_Constants
  {
    const unsigned long MODE_CHARGE = 1;
    const unsigned long MODE_UNCHARGE = 2;
  };
  module ChargerState_Constants
  {
    const unsigned long CHARGER_IDLE = 1;
    const unsigned long CHARGER_ASSIGNED = 2;
    const unsigned long CHARGER_CHARGING = 3;
    const unsigned long CHARGER_RELEASED = 4;
    const unsigned long CHARGER_ERROR = 200;
  };
  struct ChargerMode
  {
    unsigned long mode;
  };
  struct ChargerRequest
  {
    string charger_name;
    string fleet_name;
    string robot_name;
    string request_id;
    ChargerMode charger_mode;
  };
  struct ChargerState
  {
    unsigned long state;
    string charger_name;
    string error_message;
    string request_id;
    string fleet_name;
    string robot_name;
  };
};
