/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: FleetMessages.c
  Source: FleetMessages.idl
  Cyclone DDS: V0.7.0

*****************************************************************/
#include "FleetMessages.h"


static const uint32_t ChargerFleetData_ChargeMode_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (ChargerFleetData_ChargeMode, mode),
  DDS_OP_RTS
};

const dds_topic_descriptor_t ChargerFleetData_ChargeMode_desc =
{
  sizeof (ChargerFleetData_ChargeMode),
  4u,
  0u,
  0u,
  "ChargerFleetData::ChargeMode",
  NULL,
  2,
  ChargerFleetData_ChargeMode_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"ChargerFleetData\"><Struct name=\"ChargeMode\"><Member name=\"mode\"><ULong/></Member></Struct></Module></MetaData>"
};


static const uint32_t ChargerFleetData_ChargerMode_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (ChargerFleetData_ChargerMode, mode),
  DDS_OP_RTS
};

const dds_topic_descriptor_t ChargerFleetData_ChargerMode_desc =
{
  sizeof (ChargerFleetData_ChargerMode),
  4u,
  0u,
  0u,
  "ChargerFleetData::ChargerMode",
  NULL,
  2,
  ChargerFleetData_ChargerMode_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"ChargerFleetData\"><Struct name=\"ChargerMode\"><Member name=\"mode\"><ULong/></Member></Struct></Module></MetaData>"
};


static const uint32_t ChargerFleetData_ChargerState_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (ChargerFleetData_ChargerState, name),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (ChargerFleetData_ChargerState, model),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (ChargerFleetData_ChargerState, task_id),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (ChargerFleetData_ChargerState, mode.mode),
  DDS_OP_RTS
};

const dds_topic_descriptor_t ChargerFleetData_ChargerState_desc =
{
  sizeof (ChargerFleetData_ChargerState),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "ChargerFleetData::ChargerState",
  NULL,
  5,
  ChargerFleetData_ChargerState_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"ChargerFleetData\"><Struct name=\"ChargerMode\"><Member name=\"mode\"><ULong/></Member></Struct><Struct name=\"ChargerState\"><Member name=\"name\"><String/></Member><Member name=\"model\"><String/></Member><Member name=\"task_id\"><String/></Member><Member name=\"mode\"><Type name=\"ChargerMode\"/></Member></Struct></Module></MetaData>"
};


static const uint32_t ChargerFleetData_ModeRequest_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (ChargerFleetData_ModeRequest, fleet_name),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (ChargerFleetData_ModeRequest, charger_name),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (ChargerFleetData_ModeRequest, mode.mode),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (ChargerFleetData_ModeRequest, task_id),
  DDS_OP_RTS
};

const dds_topic_descriptor_t ChargerFleetData_ModeRequest_desc =
{
  sizeof (ChargerFleetData_ModeRequest),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "ChargerFleetData::ModeRequest",
  NULL,
  5,
  ChargerFleetData_ModeRequest_ops,
  "<MetaData version=\"1.0.0\"><Module name=\"ChargerFleetData\"><Struct name=\"ChargeMode\"><Member name=\"mode\"><ULong/></Member></Struct><Struct name=\"ModeRequest\"><Member name=\"fleet_name\"><String/></Member><Member name=\"charger_name\"><String/></Member><Member name=\"mode\"><Type name=\"ChargeMode\"/></Member><Member name=\"task_id\"><String/></Member></Struct></Module></MetaData>"
};
